<?php


namespace Tests\AppBundle\Entity;


use AppBundle\Entity\Task;
use AppBundle\Entity\User;
use Tests\AppBundle\Controller\WebTestCase;

class TaskTest extends WebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAddNewTask()
    {
        $user = new User();

        $task = new Task();
        $task->setTitle('titre');
        $task->setContent('description');
        $task->setUser($user);
        $task->setCreatedAt(new \DateTime('2020-01-30 12:00:00'));
        $task->toggle(false);
        $this->assertInstanceOf('DateTime', $task->getCreatedAt());
        $this->assertInstanceOf(User::class, $task->getUser());
        $this->assertSame('titre', $task->getTitle());
        $this->assertSame('description', $task->getContent());
        $this->assertFalse($task->isDone());
    }

    public function testTaskEmpty()
    {
        $task = new Task();
        $task->setTitle('');
        $task->setContent('');
        $validator = static::$kernel->getContainer()->get('validator');
        $violationList = $validator->validate($task);
        $this->assertEquals(2, $violationList->count());
        $this->assertSame('Vous devez saisir un titre.', $violationList[0]->getMessage());
        $this->assertSame('Vous devez saisir du contenu.', $violationList[1]->getMessage());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}