<?php


namespace Tests\AppBundle\Entity;


use AppBundle\Entity\Task;
use AppBundle\Entity\User;
use Tests\AppBundle\Controller\WebTestCase;

class UserTest extends WebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testUserIsEmpty()
    {
        $user = new User();

        $user->setUsername('');
        $user->setEmail('');
        $validator = static::$kernel->getContainer()->get('validator');
        $violationList = $validator->validate($user);
        $this->assertEquals(3, $violationList->count());
        $this->assertSame('Vous devez saisir un nom d\'utilisateur.', $violationList[0]->getMessage());
        $this->assertSame('Vous devez saisir une adresse email.', $violationList[1]->getMessage());
    }

    public function testNewUser()
    {
        $user = new User();
        $task = new Task();

        $user->setUsername('User');
        $user->setPassword('testPass');
        $user->setEmail('test@test.com');
        $user->setTasks($task);
        $user->setRoles(['ROLE_USER']);

        $this->assertSame('User', $user->getUsername());
        $this->assertSame('test@test.com', $user->getEmail());
        $this->assertSame('testPass', $user->getPassword());
        $this->assertInstanceOf(Task::class, $user->getTasks());
        $this->assertSame(array('ROLE_USER'), $user->getRoles());

    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}